// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: referee_command.proto

#ifndef PROTOBUF_INCLUDED_referee_5fcommand_2eproto
#define PROTOBUF_INCLUDED_referee_5fcommand_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_referee_5fcommand_2eproto 

namespace protobuf_referee_5fcommand_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_referee_5fcommand_2eproto
namespace referee_command {
class Referee_Command;
class Referee_CommandDefaultTypeInternal;
extern Referee_CommandDefaultTypeInternal _Referee_Command_default_instance_;
}  // namespace referee_command
namespace google {
namespace protobuf {
template<> ::referee_command::Referee_Command* Arena::CreateMaybeMessage<::referee_command::Referee_Command>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace referee_command {

// ===================================================================

class Referee_Command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:referee_command.Referee_Command) */ {
 public:
  Referee_Command();
  virtual ~Referee_Command();

  Referee_Command(const Referee_Command& from);

  inline Referee_Command& operator=(const Referee_Command& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Referee_Command(Referee_Command&& from) noexcept
    : Referee_Command() {
    *this = ::std::move(from);
  }

  inline Referee_Command& operator=(Referee_Command&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Referee_Command& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Referee_Command* internal_default_instance() {
    return reinterpret_cast<const Referee_Command*>(
               &_Referee_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Referee_Command* other);
  friend void swap(Referee_Command& a, Referee_Command& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Referee_Command* New() const final {
    return CreateMaybeMessage<Referee_Command>(NULL);
  }

  Referee_Command* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Referee_Command>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Referee_Command& from);
  void MergeFrom(const Referee_Command& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Referee_Command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool ready = 1;
  void clear_ready();
  static const int kReadyFieldNumber = 1;
  bool ready() const;
  void set_ready(bool value);

  // bool yellowteam = 2;
  void clear_yellowteam();
  static const int kYellowteamFieldNumber = 2;
  bool yellowteam() const;
  void set_yellowteam(bool value);

  // uint32 packet_id = 3;
  void clear_packet_id();
  static const int kPacketIdFieldNumber = 3;
  ::google::protobuf::uint32 packet_id() const;
  void set_packet_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:referee_command.Referee_Command)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool ready_;
  bool yellowteam_;
  ::google::protobuf::uint32 packet_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_referee_5fcommand_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Referee_Command

// bool ready = 1;
inline void Referee_Command::clear_ready() {
  ready_ = false;
}
inline bool Referee_Command::ready() const {
  // @@protoc_insertion_point(field_get:referee_command.Referee_Command.ready)
  return ready_;
}
inline void Referee_Command::set_ready(bool value) {
  
  ready_ = value;
  // @@protoc_insertion_point(field_set:referee_command.Referee_Command.ready)
}

// bool yellowteam = 2;
inline void Referee_Command::clear_yellowteam() {
  yellowteam_ = false;
}
inline bool Referee_Command::yellowteam() const {
  // @@protoc_insertion_point(field_get:referee_command.Referee_Command.yellowteam)
  return yellowteam_;
}
inline void Referee_Command::set_yellowteam(bool value) {
  
  yellowteam_ = value;
  // @@protoc_insertion_point(field_set:referee_command.Referee_Command.yellowteam)
}

// uint32 packet_id = 3;
inline void Referee_Command::clear_packet_id() {
  packet_id_ = 0u;
}
inline ::google::protobuf::uint32 Referee_Command::packet_id() const {
  // @@protoc_insertion_point(field_get:referee_command.Referee_Command.packet_id)
  return packet_id_;
}
inline void Referee_Command::set_packet_id(::google::protobuf::uint32 value) {
  
  packet_id_ = value;
  // @@protoc_insertion_point(field_set:referee_command.Referee_Command.packet_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace referee_command

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_referee_5fcommand_2eproto
