// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: referee_command.proto

#include "referee_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace referee_command {
class Referee_CommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Referee_Command>
      _instance;
} _Referee_Command_default_instance_;
}  // namespace referee_command
namespace protobuf_referee_5fcommand_2eproto {
static void InitDefaultsReferee_Command() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::referee_command::_Referee_Command_default_instance_;
    new (ptr) ::referee_command::Referee_Command();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::referee_command::Referee_Command::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Referee_Command =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReferee_Command}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Referee_Command.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::referee_command::Referee_Command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::referee_command::Referee_Command, ready_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::referee_command::Referee_Command, yellowteam_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::referee_command::Referee_Command, packet_id_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::referee_command::Referee_Command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::referee_command::_Referee_Command_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "referee_command.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025referee_command.proto\022\017referee_command"
      "\"G\n\017Referee_Command\022\r\n\005ready\030\001 \001(\010\022\022\n\nye"
      "llowteam\030\002 \001(\010\022\021\n\tpacket_id\030\003 \001(\rb\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 121);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "referee_command.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_referee_5fcommand_2eproto
namespace referee_command {

// ===================================================================

void Referee_Command::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Referee_Command::kReadyFieldNumber;
const int Referee_Command::kYellowteamFieldNumber;
const int Referee_Command::kPacketIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Referee_Command::Referee_Command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_referee_5fcommand_2eproto::scc_info_Referee_Command.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:referee_command.Referee_Command)
}
Referee_Command::Referee_Command(const Referee_Command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&ready_, &from.ready_,
    static_cast<size_t>(reinterpret_cast<char*>(&packet_id_) -
    reinterpret_cast<char*>(&ready_)) + sizeof(packet_id_));
  // @@protoc_insertion_point(copy_constructor:referee_command.Referee_Command)
}

void Referee_Command::SharedCtor() {
  ::memset(&ready_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&packet_id_) -
      reinterpret_cast<char*>(&ready_)) + sizeof(packet_id_));
}

Referee_Command::~Referee_Command() {
  // @@protoc_insertion_point(destructor:referee_command.Referee_Command)
  SharedDtor();
}

void Referee_Command::SharedDtor() {
}

void Referee_Command::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Referee_Command::descriptor() {
  ::protobuf_referee_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_referee_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Referee_Command& Referee_Command::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_referee_5fcommand_2eproto::scc_info_Referee_Command.base);
  return *internal_default_instance();
}


void Referee_Command::Clear() {
// @@protoc_insertion_point(message_clear_start:referee_command.Referee_Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&ready_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&packet_id_) -
      reinterpret_cast<char*>(&ready_)) + sizeof(packet_id_));
  _internal_metadata_.Clear();
}

bool Referee_Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:referee_command.Referee_Command)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool ready = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ready_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool yellowteam = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &yellowteam_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 packet_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &packet_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:referee_command.Referee_Command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:referee_command.Referee_Command)
  return false;
#undef DO_
}

void Referee_Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:referee_command.Referee_Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ready = 1;
  if (this->ready() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->ready(), output);
  }

  // bool yellowteam = 2;
  if (this->yellowteam() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->yellowteam(), output);
  }

  // uint32 packet_id = 3;
  if (this->packet_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->packet_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:referee_command.Referee_Command)
}

::google::protobuf::uint8* Referee_Command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:referee_command.Referee_Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ready = 1;
  if (this->ready() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->ready(), target);
  }

  // bool yellowteam = 2;
  if (this->yellowteam() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->yellowteam(), target);
  }

  // uint32 packet_id = 3;
  if (this->packet_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->packet_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:referee_command.Referee_Command)
  return target;
}

size_t Referee_Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:referee_command.Referee_Command)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool ready = 1;
  if (this->ready() != 0) {
    total_size += 1 + 1;
  }

  // bool yellowteam = 2;
  if (this->yellowteam() != 0) {
    total_size += 1 + 1;
  }

  // uint32 packet_id = 3;
  if (this->packet_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->packet_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Referee_Command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:referee_command.Referee_Command)
  GOOGLE_DCHECK_NE(&from, this);
  const Referee_Command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Referee_Command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:referee_command.Referee_Command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:referee_command.Referee_Command)
    MergeFrom(*source);
  }
}

void Referee_Command::MergeFrom(const Referee_Command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:referee_command.Referee_Command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ready() != 0) {
    set_ready(from.ready());
  }
  if (from.yellowteam() != 0) {
    set_yellowteam(from.yellowteam());
  }
  if (from.packet_id() != 0) {
    set_packet_id(from.packet_id());
  }
}

void Referee_Command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:referee_command.Referee_Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Referee_Command::CopyFrom(const Referee_Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:referee_command.Referee_Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Referee_Command::IsInitialized() const {
  return true;
}

void Referee_Command::Swap(Referee_Command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Referee_Command::InternalSwap(Referee_Command* other) {
  using std::swap;
  swap(ready_, other->ready_);
  swap(yellowteam_, other->yellowteam_);
  swap(packet_id_, other->packet_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Referee_Command::GetMetadata() const {
  protobuf_referee_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_referee_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace referee_command
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::referee_command::Referee_Command* Arena::CreateMaybeMessage< ::referee_command::Referee_Command >(Arena* arena) {
  return Arena::CreateInternal< ::referee_command::Referee_Command >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
