// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: referee_command.proto

#include "referee_command.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace referee_command {
PROTOBUF_CONSTEXPR Referee_Command::Referee_Command(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ready_)*/false
  , /*decltype(_impl_.yellowteam_)*/false
  , /*decltype(_impl_.packet_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Referee_CommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Referee_CommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Referee_CommandDefaultTypeInternal() {}
  union {
    Referee_Command _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Referee_CommandDefaultTypeInternal _Referee_Command_default_instance_;
}  // namespace referee_command
static ::_pb::Metadata file_level_metadata_referee_5fcommand_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_referee_5fcommand_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_referee_5fcommand_2eproto = nullptr;

const uint32_t TableStruct_referee_5fcommand_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::referee_command::Referee_Command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::referee_command::Referee_Command, _impl_.ready_),
  PROTOBUF_FIELD_OFFSET(::referee_command::Referee_Command, _impl_.yellowteam_),
  PROTOBUF_FIELD_OFFSET(::referee_command::Referee_Command, _impl_.packet_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::referee_command::Referee_Command)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::referee_command::_Referee_Command_default_instance_._instance,
};

const char descriptor_table_protodef_referee_5fcommand_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025referee_command.proto\022\017referee_command"
  "\"G\n\017Referee_Command\022\r\n\005ready\030\001 \001(\010\022\022\n\nye"
  "llowteam\030\002 \001(\010\022\021\n\tpacket_id\030\003 \001(\rb\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_referee_5fcommand_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_referee_5fcommand_2eproto = {
    false, false, 121, descriptor_table_protodef_referee_5fcommand_2eproto,
    "referee_command.proto",
    &descriptor_table_referee_5fcommand_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_referee_5fcommand_2eproto::offsets,
    file_level_metadata_referee_5fcommand_2eproto, file_level_enum_descriptors_referee_5fcommand_2eproto,
    file_level_service_descriptors_referee_5fcommand_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_referee_5fcommand_2eproto_getter() {
  return &descriptor_table_referee_5fcommand_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_referee_5fcommand_2eproto(&descriptor_table_referee_5fcommand_2eproto);
namespace referee_command {

// ===================================================================

class Referee_Command::_Internal {
 public:
};

Referee_Command::Referee_Command(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:referee_command.Referee_Command)
}
Referee_Command::Referee_Command(const Referee_Command& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Referee_Command* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ready_){}
    , decltype(_impl_.yellowteam_){}
    , decltype(_impl_.packet_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ready_, &from._impl_.ready_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.packet_id_) -
    reinterpret_cast<char*>(&_impl_.ready_)) + sizeof(_impl_.packet_id_));
  // @@protoc_insertion_point(copy_constructor:referee_command.Referee_Command)
}

inline void Referee_Command::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ready_){false}
    , decltype(_impl_.yellowteam_){false}
    , decltype(_impl_.packet_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Referee_Command::~Referee_Command() {
  // @@protoc_insertion_point(destructor:referee_command.Referee_Command)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Referee_Command::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Referee_Command::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Referee_Command::Clear() {
// @@protoc_insertion_point(message_clear_start:referee_command.Referee_Command)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ready_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.packet_id_) -
      reinterpret_cast<char*>(&_impl_.ready_)) + sizeof(_impl_.packet_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Referee_Command::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool ready = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ready_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool yellowteam = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.yellowteam_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 packet_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.packet_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Referee_Command::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:referee_command.Referee_Command)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ready = 1;
  if (this->_internal_ready() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_ready(), target);
  }

  // bool yellowteam = 2;
  if (this->_internal_yellowteam() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_yellowteam(), target);
  }

  // uint32 packet_id = 3;
  if (this->_internal_packet_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_packet_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:referee_command.Referee_Command)
  return target;
}

size_t Referee_Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:referee_command.Referee_Command)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ready = 1;
  if (this->_internal_ready() != 0) {
    total_size += 1 + 1;
  }

  // bool yellowteam = 2;
  if (this->_internal_yellowteam() != 0) {
    total_size += 1 + 1;
  }

  // uint32 packet_id = 3;
  if (this->_internal_packet_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_packet_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Referee_Command::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Referee_Command::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Referee_Command::GetClassData() const { return &_class_data_; }


void Referee_Command::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Referee_Command*>(&to_msg);
  auto& from = static_cast<const Referee_Command&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:referee_command.Referee_Command)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ready() != 0) {
    _this->_internal_set_ready(from._internal_ready());
  }
  if (from._internal_yellowteam() != 0) {
    _this->_internal_set_yellowteam(from._internal_yellowteam());
  }
  if (from._internal_packet_id() != 0) {
    _this->_internal_set_packet_id(from._internal_packet_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Referee_Command::CopyFrom(const Referee_Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:referee_command.Referee_Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Referee_Command::IsInitialized() const {
  return true;
}

void Referee_Command::InternalSwap(Referee_Command* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Referee_Command, _impl_.packet_id_)
      + sizeof(Referee_Command::_impl_.packet_id_)
      - PROTOBUF_FIELD_OFFSET(Referee_Command, _impl_.ready_)>(
          reinterpret_cast<char*>(&_impl_.ready_),
          reinterpret_cast<char*>(&other->_impl_.ready_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Referee_Command::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_referee_5fcommand_2eproto_getter, &descriptor_table_referee_5fcommand_2eproto_once,
      file_level_metadata_referee_5fcommand_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace referee_command
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::referee_command::Referee_Command*
Arena::CreateMaybeMessage< ::referee_command::Referee_Command >(Arena* arena) {
  return Arena::CreateMessageInternal< ::referee_command::Referee_Command >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
