// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: referee_command.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_referee_5fcommand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_referee_5fcommand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_referee_5fcommand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_referee_5fcommand_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_referee_5fcommand_2eproto;
namespace referee_command {
class Referee_Command;
struct Referee_CommandDefaultTypeInternal;
extern Referee_CommandDefaultTypeInternal _Referee_Command_default_instance_;
}  // namespace referee_command
PROTOBUF_NAMESPACE_OPEN
template<> ::referee_command::Referee_Command* Arena::CreateMaybeMessage<::referee_command::Referee_Command>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace referee_command {

// ===================================================================

class Referee_Command final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:referee_command.Referee_Command) */ {
 public:
  inline Referee_Command() : Referee_Command(nullptr) {}
  ~Referee_Command() override;
  explicit PROTOBUF_CONSTEXPR Referee_Command(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Referee_Command(const Referee_Command& from);
  Referee_Command(Referee_Command&& from) noexcept
    : Referee_Command() {
    *this = ::std::move(from);
  }

  inline Referee_Command& operator=(const Referee_Command& from) {
    CopyFrom(from);
    return *this;
  }
  inline Referee_Command& operator=(Referee_Command&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Referee_Command& default_instance() {
    return *internal_default_instance();
  }
  static inline const Referee_Command* internal_default_instance() {
    return reinterpret_cast<const Referee_Command*>(
               &_Referee_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Referee_Command& a, Referee_Command& b) {
    a.Swap(&b);
  }
  inline void Swap(Referee_Command* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Referee_Command* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Referee_Command* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Referee_Command>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Referee_Command& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Referee_Command& from) {
    Referee_Command::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Referee_Command* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "referee_command.Referee_Command";
  }
  protected:
  explicit Referee_Command(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReadyFieldNumber = 1,
    kYellowteamFieldNumber = 2,
    kPacketIdFieldNumber = 3,
  };
  // bool ready = 1;
  void clear_ready();
  bool ready() const;
  void set_ready(bool value);
  private:
  bool _internal_ready() const;
  void _internal_set_ready(bool value);
  public:

  // bool yellowteam = 2;
  void clear_yellowteam();
  bool yellowteam() const;
  void set_yellowteam(bool value);
  private:
  bool _internal_yellowteam() const;
  void _internal_set_yellowteam(bool value);
  public:

  // uint32 packet_id = 3;
  void clear_packet_id();
  uint32_t packet_id() const;
  void set_packet_id(uint32_t value);
  private:
  uint32_t _internal_packet_id() const;
  void _internal_set_packet_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:referee_command.Referee_Command)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool ready_;
    bool yellowteam_;
    uint32_t packet_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_referee_5fcommand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Referee_Command

// bool ready = 1;
inline void Referee_Command::clear_ready() {
  _impl_.ready_ = false;
}
inline bool Referee_Command::_internal_ready() const {
  return _impl_.ready_;
}
inline bool Referee_Command::ready() const {
  // @@protoc_insertion_point(field_get:referee_command.Referee_Command.ready)
  return _internal_ready();
}
inline void Referee_Command::_internal_set_ready(bool value) {
  
  _impl_.ready_ = value;
}
inline void Referee_Command::set_ready(bool value) {
  _internal_set_ready(value);
  // @@protoc_insertion_point(field_set:referee_command.Referee_Command.ready)
}

// bool yellowteam = 2;
inline void Referee_Command::clear_yellowteam() {
  _impl_.yellowteam_ = false;
}
inline bool Referee_Command::_internal_yellowteam() const {
  return _impl_.yellowteam_;
}
inline bool Referee_Command::yellowteam() const {
  // @@protoc_insertion_point(field_get:referee_command.Referee_Command.yellowteam)
  return _internal_yellowteam();
}
inline void Referee_Command::_internal_set_yellowteam(bool value) {
  
  _impl_.yellowteam_ = value;
}
inline void Referee_Command::set_yellowteam(bool value) {
  _internal_set_yellowteam(value);
  // @@protoc_insertion_point(field_set:referee_command.Referee_Command.yellowteam)
}

// uint32 packet_id = 3;
inline void Referee_Command::clear_packet_id() {
  _impl_.packet_id_ = 0u;
}
inline uint32_t Referee_Command::_internal_packet_id() const {
  return _impl_.packet_id_;
}
inline uint32_t Referee_Command::packet_id() const {
  // @@protoc_insertion_point(field_get:referee_command.Referee_Command.packet_id)
  return _internal_packet_id();
}
inline void Referee_Command::_internal_set_packet_id(uint32_t value) {
  
  _impl_.packet_id_ = value;
}
inline void Referee_Command::set_packet_id(uint32_t value) {
  _internal_set_packet_id(value);
  // @@protoc_insertion_point(field_set:referee_command.Referee_Command.packet_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace referee_command

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_referee_5fcommand_2eproto
