// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vssref_placement.proto

#include "vssref_placement.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace VSSRef {
namespace team_to_ref {
PROTOBUF_CONSTEXPR VSSRef_Placement::VSSRef_Placement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.world_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VSSRef_PlacementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VSSRef_PlacementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VSSRef_PlacementDefaultTypeInternal() {}
  union {
    VSSRef_Placement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VSSRef_PlacementDefaultTypeInternal _VSSRef_Placement_default_instance_;
}  // namespace team_to_ref
}  // namespace VSSRef
static ::_pb::Metadata file_level_metadata_vssref_5fplacement_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_vssref_5fplacement_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_vssref_5fplacement_2eproto = nullptr;

const uint32_t TableStruct_vssref_5fplacement_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::VSSRef::team_to_ref::VSSRef_Placement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::VSSRef::team_to_ref::VSSRef_Placement, _impl_.world_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::VSSRef::team_to_ref::VSSRef_Placement)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::VSSRef::team_to_ref::_VSSRef_Placement_default_instance_._instance,
};

const char descriptor_table_protodef_vssref_5fplacement_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026vssref_placement.proto\022\022VSSRef.team_to"
  "_ref\032\023vssref_common.proto\"0\n\020VSSRef_Plac"
  "ement\022\034\n\005world\030\001 \001(\0132\r.VSSRef.Frameb\006pro"
  "to3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_vssref_5fplacement_2eproto_deps[1] = {
  &::descriptor_table_vssref_5fcommon_2eproto,
};
static ::_pbi::once_flag descriptor_table_vssref_5fplacement_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_vssref_5fplacement_2eproto = {
    false, false, 123, descriptor_table_protodef_vssref_5fplacement_2eproto,
    "vssref_placement.proto",
    &descriptor_table_vssref_5fplacement_2eproto_once, descriptor_table_vssref_5fplacement_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_vssref_5fplacement_2eproto::offsets,
    file_level_metadata_vssref_5fplacement_2eproto, file_level_enum_descriptors_vssref_5fplacement_2eproto,
    file_level_service_descriptors_vssref_5fplacement_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_vssref_5fplacement_2eproto_getter() {
  return &descriptor_table_vssref_5fplacement_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_vssref_5fplacement_2eproto(&descriptor_table_vssref_5fplacement_2eproto);
namespace VSSRef {
namespace team_to_ref {

// ===================================================================

class VSSRef_Placement::_Internal {
 public:
  static const ::VSSRef::Frame& world(const VSSRef_Placement* msg);
};

const ::VSSRef::Frame&
VSSRef_Placement::_Internal::world(const VSSRef_Placement* msg) {
  return *msg->_impl_.world_;
}
void VSSRef_Placement::clear_world() {
  if (GetArenaForAllocation() == nullptr && _impl_.world_ != nullptr) {
    delete _impl_.world_;
  }
  _impl_.world_ = nullptr;
}
VSSRef_Placement::VSSRef_Placement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:VSSRef.team_to_ref.VSSRef_Placement)
}
VSSRef_Placement::VSSRef_Placement(const VSSRef_Placement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VSSRef_Placement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.world_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_world()) {
    _this->_impl_.world_ = new ::VSSRef::Frame(*from._impl_.world_);
  }
  // @@protoc_insertion_point(copy_constructor:VSSRef.team_to_ref.VSSRef_Placement)
}

inline void VSSRef_Placement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.world_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VSSRef_Placement::~VSSRef_Placement() {
  // @@protoc_insertion_point(destructor:VSSRef.team_to_ref.VSSRef_Placement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VSSRef_Placement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.world_;
}

void VSSRef_Placement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VSSRef_Placement::Clear() {
// @@protoc_insertion_point(message_clear_start:VSSRef.team_to_ref.VSSRef_Placement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.world_ != nullptr) {
    delete _impl_.world_;
  }
  _impl_.world_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VSSRef_Placement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .VSSRef.Frame world = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_world(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VSSRef_Placement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:VSSRef.team_to_ref.VSSRef_Placement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .VSSRef.Frame world = 1;
  if (this->_internal_has_world()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::world(this),
        _Internal::world(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VSSRef.team_to_ref.VSSRef_Placement)
  return target;
}

size_t VSSRef_Placement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VSSRef.team_to_ref.VSSRef_Placement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .VSSRef.Frame world = 1;
  if (this->_internal_has_world()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.world_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VSSRef_Placement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VSSRef_Placement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VSSRef_Placement::GetClassData() const { return &_class_data_; }


void VSSRef_Placement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VSSRef_Placement*>(&to_msg);
  auto& from = static_cast<const VSSRef_Placement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:VSSRef.team_to_ref.VSSRef_Placement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_world()) {
    _this->_internal_mutable_world()->::VSSRef::Frame::MergeFrom(
        from._internal_world());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VSSRef_Placement::CopyFrom(const VSSRef_Placement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VSSRef.team_to_ref.VSSRef_Placement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VSSRef_Placement::IsInitialized() const {
  return true;
}

void VSSRef_Placement::InternalSwap(VSSRef_Placement* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.world_, other->_impl_.world_);
}

::PROTOBUF_NAMESPACE_ID::Metadata VSSRef_Placement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_vssref_5fplacement_2eproto_getter, &descriptor_table_vssref_5fplacement_2eproto_once,
      file_level_metadata_vssref_5fplacement_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace team_to_ref
}  // namespace VSSRef
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::VSSRef::team_to_ref::VSSRef_Placement*
Arena::CreateMaybeMessage< ::VSSRef::team_to_ref::VSSRef_Placement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::VSSRef::team_to_ref::VSSRef_Placement >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
